genres = Genre.create([{ name: "Classic" },
                       { name: "Fantasy" },
                       { name: "Science Fiction" },
                       { name: "Horror" },
                       { name: "Mystery/Suspense" },
                       { name: "Young Adult" },
                       { name: "Romance" },
                       { name: "Comic/Graphic Novel" },
                       { name: "Children's Books" },
                       { name: "Poetry" },
                       { name: "Biography" },
                       { name: "History" },
                       { name: "Politics" },
                       { name: "Self Help" },
                       { name: "Education/Reference" }])
